
package webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CityServcie", targetNamespace = "http://service.webservice/")
public interface CityServcie {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCity", targetNamespace = "http://service.webservice/", className = "webservice.client.GetCity")
    @ResponseWrapper(localName = "getCityResponse", targetNamespace = "http://service.webservice/", className = "webservice.client.GetCityResponse")
    @Action(input = "http://service.webservice/CityServcie/getCityRequest", output = "http://service.webservice/CityServcie/getCityResponse")
    public String getCity(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
