
package webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CityServcieService", targetNamespace = "http://service.webservice/", wsdlLocation = "http://localhost:8989/city?wsdl")
public class CityServcieService
    extends Service
{

    private final static URL CITYSERVCIESERVICE_WSDL_LOCATION;
    private final static WebServiceException CITYSERVCIESERVICE_EXCEPTION;
    private final static QName CITYSERVCIESERVICE_QNAME = new QName("http://service.webservice/", "CityServcieService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8989/city?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CITYSERVCIESERVICE_WSDL_LOCATION = url;
        CITYSERVCIESERVICE_EXCEPTION = e;
    }

    public CityServcieService() {
        super(__getWsdlLocation(), CITYSERVCIESERVICE_QNAME);
    }

    public CityServcieService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CITYSERVCIESERVICE_QNAME, features);
    }

    public CityServcieService(URL wsdlLocation) {
        super(wsdlLocation, CITYSERVCIESERVICE_QNAME);
    }

    public CityServcieService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CITYSERVCIESERVICE_QNAME, features);
    }

    public CityServcieService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CityServcieService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CityServcie
     */
    @WebEndpoint(name = "CityServciePort")
    public CityServcie getCityServciePort() {
        return super.getPort(new QName("http://service.webservice/", "CityServciePort"), CityServcie.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CityServcie
     */
    @WebEndpoint(name = "CityServciePort")
    public CityServcie getCityServciePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.webservice/", "CityServciePort"), CityServcie.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CITYSERVCIESERVICE_EXCEPTION!= null) {
            throw CITYSERVCIESERVICE_EXCEPTION;
        }
        return CITYSERVCIESERVICE_WSDL_LOCATION;
    }

}
